### ISSUE TITLE
Lw12 neue Version

### ISSUE THREAD

**Issue by BenWallmeyer** [herrmannj/wifilight#2]
Anscheinend gibt es  eine neue Version vom LW12 diese scheint nicht zu funktionieren mit dem Modul. Gibt es dafür schon eine Lösung?

**Comment by herrmannj** [comment]
welche ssid hat der lw12 selbst ?

**Comment by BenWallmeyer** [comment]
Habe es lösen können bei der neuen Version ist es FW12FC

Vielen Dank
